### ISSUE TITLE
The integer LONG_MIN evaluates to 0

### ISSUE THREAD

**Issue by mwm** [jpoirier/picoc#13]
Trying to input the value of LONG_MIN on your platform, you get 0.

```
picoc> long x;
picoc> x = -9223372036854775808L;
picoc> printf("%ld\n", x);
0

```

Compiled, that code produces the expected -9223372036854775808.

**Comment by jpoirier** [comment]
give the develop branch a try

**Comment by mwm** [comment]
Develop doesn't work any better:

```
starting picoc v2.2.1 re4a559a1 (Ctrl+D to exit)
picoc> long min = -9223372036854775808L;
picoc> long max = 9223372036854775807L;
picoc> printf("min = %ld, max = %ld,  min + max = %ld\n", min, max, min + max);
min = 0, max = 9223372036854775807,  min + max = -1
```

I did a bit more testing: you can see that the max value is correct, and adding it to the min value gets the expected result, but min prints wrong.

**Comment by jpoirier** [comment]
yup
