### ISSUE TITLE
 bad type declaration about function pointer

### ISSUE THREAD

**Issue by ClaudioDaffra** [jpoirier/picoc#14]
i am trying to execute somes examples this gives me error
 
 following files ( 42_function_:pointer.c ) : bad type declaration

	#include <stdio.h>

	int fred(int p)
	{
		printf("yo %d\n", p);
		return 42;
	}

	int (*f)(int) = &fred; <-- ERROR

	int main()
	{
		printf("%d\n", &fred);
		return 0;
	}

compiled with mingw32 , window10 , in qt5.10

**Comment by jpoirier** [comment]
Sorry but function pointers aren't supported, see the readme section
https://github.com/jpoirier/picoc#function-pointers

-joe
