### ISSUE TITLE
Relation to zsaleeba/picoc?

### ISSUE THREAD

**Issue by benhowes** [jpoirier/picoc#25]
Hello! Am I right in thinking that this repo is a continuation of the work started here https://github.com/zsaleeba/picoc? Thanks

**Comment by jpoirier** [comment]
Yes. At the top of the readme page it states that it was originally forked
from  https://github.com/zsaleeba/picoc and the repo itself includes all
the original commit history.

-joe

**Comment by benhowes** [comment]
Thanks - I had missed that (of course!)
